---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mydockerrepo-backend
  namespace: mydockerrepo
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: mydockerrepo
      layer: backend
  replicas: 2
  revisionHistoryLimit: 5
  template: 
    metadata:
      labels:
        app: mydockerrepo
        layer: backend
    spec:
      containers:
      - name: mydockerrepo-backend-container
        image: abhijitrout/mydockerrepo-backend:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"
        env:
          - name: "MY_DB_USER"
            value: "mysqluser"
          - name: "MY_DB_PASS"
            value: "password"
          - name: "MY_DB_NAME"
            value: "mydatadb"
          - name: "MY_DB_HOST_WRITE"
            value: "mysql-0.mysql"
          - name: "MY_DB_HOST_READ"
            value: "mysql-read"
        
