---
kind: Service
apiVersion: v1
metadata:
  name: backendapi
  namespace: mydockerrepo
spec:
  selector:
    app: mydockerrepo
    layer: backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  

