---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.names.msname }}-{{ .Values.names.fename }}
  namespace: {{ .Values.msname }}
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: {{ .Values.names.msname }}
      layer: {{ .Values.names.fename }}
  replicas: 2
  revisionHistoryLimit: 5
  template: 
    metadata:
      labels:
        app: {{ .Values.names.msname }}
        layer: {{ .Values.names.fename }}
    spec:
      containers:
      - name: mydockerrepo-frontend-container
        image: BUILDTAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"
        env:
          - name: BACKENDLB
            value: {{ .Values.names.bename }}
            
